import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import {
	buildClientEnv,
	buildServerEnv,
	parseSupabaseEnv,
	writeEnvFiles,
} from "./setup-local-env.mjs";

const FIXTURE = `API_URL="http://127.0.0.1:54321"
ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.anon.sig"
DB_URL="postgresql://postgres:postgres@127.0.0.1:54322/postgres"
GRAPHQL_URL="http://127.0.0.1:54321/graphql/v1"
INBUCKET_URL="http://127.0.0.1:54324"
JWT_SECRET="super-secret-jwt-token"
SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.service.sig"
STUDIO_URL="http://127.0.0.1:54323"
`;

test("parseSupabaseEnv extracts keys from `supabase status -o env` output", () => {
	const parsed = parseSupabaseEnv(FIXTURE);

	assert.equal(parsed.apiUrl, "http://127.0.0.1:54321");
	assert.equal(parsed.anonKey, "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.anon.sig");
	assert.equal(
		parsed.serviceRoleKey,
		"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.service.sig",
	);
	assert.equal(parsed.jwtSecret, "super-secret-jwt-token");
});

test("parseSupabaseEnv tolerates unquoted values and surrounding whitespace", () => {
	const parsed = parseSupabaseEnv(
		[
			"",
			"  API_URL=http://127.0.0.1:54321  ",
			"ANON_KEY=anon-bare",
			'SERVICE_ROLE_KEY="service-quoted"',
			"",
		].join("\n"),
	);

	assert.equal(parsed.apiUrl, "http://127.0.0.1:54321");
	assert.equal(parsed.anonKey, "anon-bare");
	assert.equal(parsed.serviceRoleKey, "service-quoted");
});

test("parseSupabaseEnv throws a helpful error when required keys are missing", () => {
	assert.throws(
		() => parseSupabaseEnv('API_URL="http://127.0.0.1:54321"\n'),
		/ANON_KEY/,
	);
	assert.throws(
		() => parseSupabaseEnv('ANON_KEY="x"\nSERVICE_ROLE_KEY="y"\n'),
		/API_URL/,
	);
});

test("buildClientEnv emits Vite-prefixed variables for local Supabase", () => {
	const env = buildClientEnv({
		apiUrl: "http://127.0.0.1:54321",
		anonKey: "anon-123",
	});

	assert.match(env, /^VITE_SUPABASE_URL=http:\/\/127\.0\.0\.1:54321$/m);
	assert.match(env, /^VITE_SUPABASE_ANON_KEY=anon-123$/m);
	assert.match(env, /^VITE_SLACK_CALLBACK_URL=http:\/\/localhost:5173\/$/m);
	assert.match(env, /^VITE_API_PROXY_TARGET=http:\/\/127\.0\.0\.1:8787$/m);
	assert.match(env, /Generated by scripts\/setup-local-env\.mjs/);
});

test("buildServerEnv wires server vars and uses fallback encryption key", () => {
	const env = buildServerEnv({
		apiUrl: "http://127.0.0.1:54321",
		serviceRoleKey: "service-abc",
		encryptionKey: "fixed-local-dev-secret-do-not-use-in-prod",
	});

	assert.match(env, /^SUPABASE_URL=http:\/\/127\.0\.0\.1:54321$/m);
	assert.match(env, /^SUPABASE_SERVICE_ROLE_KEY=service-abc$/m);
	assert.match(
		env,
		/^FIELD_ENCRYPTION_KEY=fixed-local-dev-secret-do-not-use-in-prod$/m,
	);
	assert.match(env, /^PORT=8787$/m);
	assert.match(
		env,
		/^CORS_ORIGIN=http:\/\/localhost:5173,http:\/\/127\.0\.0\.1:5173$/m,
	);
});

test("buildServerEnv reuses an existing FIELD_ENCRYPTION_KEY when provided", () => {
	const env = buildServerEnv({
		apiUrl: "http://127.0.0.1:54321",
		serviceRoleKey: "service-abc",
		existingEnv:
			"FIELD_ENCRYPTION_KEY=reused-secret-from-previous-run\nOTHER=ignored\n",
	});

	assert.match(env, /^FIELD_ENCRYPTION_KEY=reused-secret-from-previous-run$/m);
});

test("buildServerEnv preserves LOCAL_ADMIN_EMAILS when already configured", () => {
	const env = buildServerEnv({
		apiUrl: "http://127.0.0.1:54321",
		serviceRoleKey: "service-abc",
		existingEnv:
			"FIELD_ENCRYPTION_KEY=reused-secret-from-previous-run\nLOCAL_ADMIN_EMAILS=jakob.friedrich05@gmail.com\n",
	});

	assert.match(env, /^LOCAL_ADMIN_EMAILS=jakob\.friedrich05@gmail\.com$/m);
});

test("buildServerEnv preserves ENABLE_LOCAL_ADMIN_BOOTSTRAP when configured", () => {
	const env = buildServerEnv({
		apiUrl: "http://127.0.0.1:54321",
		serviceRoleKey: "service-abc",
		existingEnv:
			"FIELD_ENCRYPTION_KEY=reused-secret-from-previous-run\nENABLE_LOCAL_ADMIN_BOOTSTRAP=true\n",
	});

	assert.match(env, /^ENABLE_LOCAL_ADMIN_BOOTSTRAP=true$/m);
});

test("writeEnvFiles writes client and server .env.local and is idempotent", () => {
	const tmp = mkdtempSync(join(tmpdir(), "member-manager-env-"));
	try {
		const clientPath = join(tmp, "client", ".env.local");
		const serverPath = join(tmp, "server", ".env.local");

		writeEnvFiles({
			parsed: parseSupabaseEnv(FIXTURE),
			clientEnvPath: clientPath,
			serverEnvPath: serverPath,
			defaultEncryptionKey: "local-dev-secret",
		});

		const clientFirst = readFileSync(clientPath, "utf8");
		const serverFirst = readFileSync(serverPath, "utf8");

		assert.match(clientFirst, /VITE_SUPABASE_URL=http:\/\/127\.0\.0\.1:54321/);
		assert.match(serverFirst, /SUPABASE_SERVICE_ROLE_KEY=eyJ/);
		assert.match(serverFirst, /FIELD_ENCRYPTION_KEY=local-dev-secret/);

		writeEnvFiles({
			parsed: parseSupabaseEnv(FIXTURE),
			clientEnvPath: clientPath,
			serverEnvPath: serverPath,
			defaultEncryptionKey: "different-default-should-be-ignored",
		});

		const serverSecond = readFileSync(serverPath, "utf8");

		assert.match(
			serverSecond,
			/FIELD_ENCRYPTION_KEY=local-dev-secret/,
			"existing FIELD_ENCRYPTION_KEY must be preserved across re-runs",
		);
	} finally {
		rmSync(tmp, { recursive: true, force: true });
	}
});

test("writeEnvFiles honours existingServerEnv override over the default", () => {
	const tmp = mkdtempSync(join(tmpdir(), "member-manager-env-"));
	try {
		const serverPath = join(tmp, "server", ".env.local");
		const clientPath = join(tmp, "client", ".env.local");

		writeEnvFiles({
			parsed: parseSupabaseEnv(FIXTURE),
			clientEnvPath: clientPath,
			serverEnvPath: serverPath,
			defaultEncryptionKey: "fallback-should-be-ignored",
			existingServerEnv:
				"FIELD_ENCRYPTION_KEY=pre-existing-user-secret\nCORS_ORIGIN=http://example\n",
		});

		const serverContent = readFileSync(serverPath, "utf8");
		assert.match(
			serverContent,
			/FIELD_ENCRYPTION_KEY=pre-existing-user-secret/,
		);
	} finally {
		rmSync(tmp, { recursive: true, force: true });
	}
});
